// this is here for the same reason ms_opcode.h exists

#ifndef TOKEN
#define TOKEN(t)
#endif

// single and double character tokens

TOKEN(MS_TOK__CHARTOKS_START)

/****** do not modify the order of these!!! ******/
TOKEN(MS_TOK_PLUS)    TOKEN(MS_TOK_PLUS_ASSIGN)
TOKEN(MS_TOK_MINUS)   TOKEN(MS_TOK_MINUS_ASSIGN)
TOKEN(MS_TOK_STAR)    TOKEN(MS_TOK_STAR_ASSIGN)
TOKEN(MS_TOK_SLASH)   TOKEN(MS_TOK_SLASH_ASSIGN)
TOKEN(MS_TOK_PERCENT) TOKEN(MS_TOK_PERCENT_ASSIGN)
TOKEN(MS_TOK_CARET)   TOKEN(MS_TOK_CARET_ASSIGN)
TOKEN(MS_TOK_ASSIGN)  TOKEN(MS_TOK_EQUAL)
TOKEN(MS_TOK_GREATER) TOKEN(MS_TOK_GEQ)
TOKEN(MS_TOK_LESS)    TOKEN(MS_TOK_LEQ)
/*************************************************/

TOKEN(MS_TOK_NEQ) // it is alone :(

TOKEN(MS_TOK_DOT)
TOKEN(MS_TOK_COLON)
TOKEN(MS_TOK_COMMA)

TOKEN(MS_TOK_LPAREN)  TOKEN(MS_TOK_RPAREN)
TOKEN(MS_TOK_LBRACE)  TOKEN(MS_TOK_RBRACE)
TOKEN(MS_TOK_LSQUARE) TOKEN(MS_TOK_RSQUARE)

TOKEN(MS_TOK_AT_SIGN)
TOKEN(MS_TOK_NEWLINE)

TOKEN(MS_TOK__CHARTOKS_END)

// keywords
TOKEN(MS_TOK__KEYWORD_START)

TOKEN(MS_TOK_TRUE)
TOKEN(MS_TOK_FALSE)
TOKEN(MS_TOK_NULL)

TOKEN(MS_TOK_AND)
TOKEN(MS_TOK_OR)
TOKEN(MS_TOK_NOT)

TOKEN(MS_TOK_ELSE)
TOKEN(MS_TOK_ELSE_IF)
TOKEN(MS_TOK_THEN)
TOKEN(MS_TOK_IN)
TOKEN(MS_TOK_RETURN)

TOKEN(MS_TOK_ISA)
TOKEN(MS_TOK_NEW)
TOKEN(MS_TOK_SUPER)
TOKEN(MS_TOK_SELF)

TOKEN(MS_TOK_GLOBALS)
TOKEN(MS_TOK_LOCALS)

TOKEN(MS_TOK__BLOCK_START)
/*** do not modify the order of these!!! ***/
TOKEN(MS_TOK_FUNC)   TOKEN(MS_TOK_END_FUNC)
TOKEN(MS_TOK_IF)     TOKEN(MS_TOK_END_IF)
TOKEN(MS_TOK_WHILE)  TOKEN(MS_TOK_END_WHILE)
TOKEN(MS_TOK_FOR)    TOKEN(MS_TOK_END_FOR)
TOKEN(MS_TOK_REPEAT) TOKEN(MS_TOK_END_REPEAT)
/*******************************************/
TOKEN(MS_TOK__BLOCK_END)

TOKEN(MS_TOK__KEYWORD_END)

// "user" tokens, i.e. tokens that aren't keywords
// but are still useful to know about
TOKEN(MS_TOK__USER_START)

TOKEN(MS_TOK_NUM)
TOKEN(MS_TOK_ID)
TOKEN(MS_TOK_STR)

TOKEN(MS_TOK__USER_END)

// tokens used internally
TOKEN(MS_TOK_ERROR)
TOKEN(MS_TOK_EOF)

TOKEN(MS_TOK__END)
